export const START = "START";
export const DISPLAY_ADD_ACCOUNTS_ACTION = "DISPLAY_ADD_ACCOUNTS";
export const DISPLAY_ACCOUNTS_ACTION = "DISPLAY_ACCOUNTS";
export const ADD_NEW_ACCOUNT = "ADD_NEW_ACCOUNT";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT" ;


export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_ERROR = "FETCH_USERS_ERROR"